version: '3.7'

services:
  docs-api:
    restart: always
    image: holmes89/tags
    build:
      context: .
      dockerfile: Dockerfile
      target: prod
    ports:
      - 8081:8080
  db:
    image: cayleygraph/cayley
    restart: always
    ports:
      - 64210:64210
